let sumar = require('./sumar.js');
let restar = require('./restar.js');
let multiplicar = require('./multiplicar.js');
let dividir = require('./dividir.js');
sumar(10, 5);
restar(10, 5);
multiplicar(10, 10);
multiplicar(10, 0);
dividir(20, 4);
dividir(10, 0);